services:
  webtop:
    image: lscr.io/linuxserver/webtop:debian-kde
    #version tag changes the linux image:
    #common tags:
      # fedora-kde
      # arch-kde
      # ubuntu-kde
      # arch-i3
      # debian-i3
      # fedora-i3
      # debian-xfce
    container_name: webtop
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
     # - SUBFOLDER=/ #optional
     # - TITLE=Webtop #optional
    volumes:
      - ./webtop/config:/config
      - /var/run/docker.sock:/var/run/docker.sock #optional
    ports:
      - 3310:3000 #HTTP
      - 3311:3001 #HTTPS
    restart: unless-stopped
